
[workspace]
resolver = "3"

members = [
        "crates/ts-engine",
        "crates/ts-object-macros",
        "crates/ts-object",
        "crates/ts-script",
        "crates/ts-process"
    ]

default-members = [
        "crates/ts-engine"
    ]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
authors = [ "Chloë Strainge <nullptr.0@gmail.com>" ]
repository = "https://github.com/cstrainge/ts-engine"
